### ISSUE TITLE
Problem with importing MPDataRetrieval

### ISSUE THREAD

**Issue by ZahraGhSh** [PV-Lab/FTCP#3]
I am a Linux user and tried to run the data.py file on colab.
I get an error while importing MPDataRetrieval.
So this is what I tried:
```
!pip install matminer
from matminer.data_retrieval.retrieve_MP import MPDataRetrieval
```

And this is the error:

```
ImportError                               Traceback (most recent call last)

[<ipython-input-12-92dab7dbcc0d>](https://localhost:8080/#) in <module>()
----> 1 from matminer.data_retrieval.retrieve_MP import MPDataRetrieval
      2 
      3 def data_query(mp_api_key, max_elms=3, min_elms=3, max_sites=20, include_te=False):
      4     """
      5     The function queries data from Materials Project.

4 frames

[/usr/local/lib/python3.7/dist-packages/scipy/cluster/vq.py](https://localhost:8080/#) in <module>()
     68 import numpy as np
     69 from collections import deque
---> 70 from scipy._lib._util import _asarray_validated, check_random_state,\
     71     rng_integers
     72 from scipy.spatial.distance import cdist

ImportError: cannot import name 'rng_integers' from 'scipy._lib._util' (/usr/local/lib/python3.7/dist-packages/scipy/_lib/_util.py)
```

**Comment by sgbaird** [comment]
@ZahraGhSh per the installation instructions, did you clone the repository first:
```bash
!git clone https://github.com/PV-Lab/FTCP.git
```
navigate to the folder:
```bash
cd FTCP
```
and then install the dependencies via:
```bash
!pip install -r requirement.txt
```
?

When you try to run `main.py` per the usage instructions (after completing the above steps), do you get an error?
See https://www.google.com/search?q=run+python+script+google+colab

**Comment by ZahraGhSh** [comment]
@sgbaird Well, I was trying to run ```data.py``` not ```main.py```.

**Comment by sgbaird** [comment]
@ZahraGhSh ok, shouldn't make a difference - `main.py` imports everything from `data.py`. Can you provide a reproducer Google Colab script?

**Comment by ZahraGhSh** [comment]
@sgbaird I have tried those steps for data.py and got the same error. I am not sure what you mean by reproducer Google Colab script. Would you help me with that?

**Comment by sgbaird** [comment]
> @sgbaird I have tried those steps for data.py and got the same error. I am not sure what you mean by reproducer Google Colab script. Would you help me with that?
> 
>  

A repro or reproducer is a script that allows developers to replicate whatever error or issue you're running into so they can run it themselves and figure out how to debug it. Related is a minimal working example (MWE). Google Colab has some really easy sharing capabilities, so the idea is you write up a simple example that shows the error on Google Colab and then share the link here.

**Comment by ZahraGhSh** [comment]
@sgbaird Thank you for the explanation. This is the [link](https://github.com/ZahraGhSh/FTCP-Representation/blob/main/MWE_FTCP_data_py.ipynb) to the piece of script. It is mostly similar to the very first lines of ```data.py``` file.

**Comment by sgbaird** [comment]
Running into a bunch of issues, fix one, another pops up ([Colab script](https://colab.research.google.com/gist/sgbaird/85a6fbd1dee561382361fdd3c90c8d14/mwe_ftcp_data-py.ipynb)). @bonners @buonassisi @mgthway would recommend doing some troubleshooting to get it up and running with a Google Colab script if you're interested. In the meantime @ZahraGhSh you might want to try foregoing Google Colab and trying to run it locally.

Btw, pretty sure there's a bug in their `requirements.txt` file. `json` comes packaged with Python, so it throws an error and nothing gets installed.

**Comment by SiyuIsaacParkerTian** [comment]
@ZahraGhSh @sgbaird Short answer is that on Google Colab you need to switch to tensorflow 1.x first before installing packages according to the requirement.txt. The only code you need to run for installing the packages are the following:

```
%tensorflow_version 1.x
!pip install pymatgen==2019.12.22
!pip install matminer==0.6.2
!pip install ase
```

Hope this solves your problem. Also putting this into readme.

**Comment by sgbaird** [comment]
@ZahraGhSh were you able to get it running?

**Comment by ZahraGhSh** [comment]
@SiyuIsaacParkerTian @sgbaird  Thank you for your response. I tried what you added. now I am getting this error :
`MPRestError: REST query returned with error status code 504. Content: b'<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n'`

**Comment by sgbaird** [comment]
@ZahraGhSh 

https://matsci.org/t/error-504-gateway-time-out/1659

**Comment by sgbaird** [comment]
@ZahraGhSh hard to say much else without seeing the stack trace / what lines are producing the error

**Comment by ZahraGhSh** [comment]
@sgbaird , @SiyuIsaacParkerTian , It is working now. Thanks much.
